### ISSUE TITLE
Add unit test on centralized telescope parameter generation

### ISSUE THREAD

**Issue by rrtoledo** [cardano-scaling/alba#98]
## Why

We have unit tests for the parameter generation of the lottery but not centralized setting.

## What

Add unit tests.

## Tasks

- [ ] Test low case
    - [ ] equal lambdas
    - [ ] lsec > lrel
    - [ ] lsec < lrel 
- [ ] Test mid case
    - [ ] equal lambdas
    - [ ] lsec > lrel
    - [ ] lsec < lrel 
- [ ] Test high case
    - [ ] equal lambdas
    - [ ] lsec > lrel
    - [ ] lsec < lrel
